defaults:
  - hydra/job_logging: custom_async.yaml
  - misc
  - layers_defaults
  - model: quant_mobilenet_v1_4b
  - optim: rmsproptf
  - scheduler: multistep

log:
  INTERVAL: 2
  SAVE_INTERVAL: 10
  TRAINS_LOGGING: False
  TEST_TUBE_LOGGING: False

TRAIN_BATCH_SIZE: 256
IS_DISTRIBUTED: False
MIXED_PRECISION: False
EPOCHS: 30

LABEL_SMOOTHING: 0.1
MAX_L2_SCALING_REG: 0.0
DATASET_TRAIN_SIZE: 1281167

WARMUP_EPOCHS: 0

NO_WD:
  - 'bn'
  - 'bias'
  - 'scaling'

EVALUATE_ONLY: False
RESUME_OPTIM: False
RESUME_TRAINING_PROGRESS: False



