defaults:
  - misc
  - layers_defaults
  - model: quant_mobilenet_v1_4b
  - optim: rmsproptf
  - scheduler: multistep

log:
  INTERVAL: 2
  SAVE_INTERVAL: 10
  TRAINS_LOGGING: False

TRAIN_BATCH_SIZE: 256
IS_DISTRIBUTED: False
MIXED_PRECISION: False
EPOCHS: 30

LABEL_SMOOTHING: 0.1
MAX_AVE_SCALING_REG: 0.0

WARMUP_EPOCHS: 0

dropout:
  RATE: 0.2
  SAMPLES: 1

NO_WD:
  - 'bn'
  - 'bias'
  - 'scaling'

EVALUATE_ONLY: False



