TRAIN_BATCH_SIZE: 256
IS_DISTRIBUTED: False
MIXED_PRECISION: False
EPOCHS: 30

LABEL_SMOOTHING: 0.0

OPTIMIZER: SGD
optim_conf:
  LR: 0.001
  WEIGHT_DECAY: 0.0001
  NESTEROV: False

SCHEDULER: MULTISTEP
WARMUP_EPOCHS: 0
scheduler_conf:
  GAMMA: 0.1
  MILESTONES:
    - 10
    - 20

dropout:
  RATE: 0.2
  SAMPLES: 16

NO_WD:
  - 'bn'
  - 'bias'
  - 'scaling'