FROM pytorch/pytorch:1.3-cuda10.1-cudnn7-devel

RUN pip install test-tube==0.7.3 hydra-core
RUN pip install --no-deps pytorch-lightning==0.5.3.2
RUN git clone https://github.com/NVIDIA/apex && \
    cd apex && \
    pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./
RUN conda install scipy
RUN pip install docrep flatdict geffnet timm
